apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "assignment-10-empty-node-chart.fullname" . }}
  labels:
    {{- include "assignment-10-empty-node-chart.labels" . | nindent 4 }} # פותר בעית אינדנטציה, כופה אינדנטציה שיתאים תמיד
spec:
  {{- if not .Values.autoscaling.enabled }} # if the autoscaling not enabled he will change the replica count accordingly
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "assignment-10-empty-node-chart.selectorLabels" . | nindent 6 }} # to know which label the app is for?
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "assignment-10-empty-node-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }} # if we need secrets to pull image, to connect to some registery
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "assignment-10-empty-node-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" # takes the values from nginx
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http  # hardocded..less good
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
