{{- range $fullName, $svc := .Values.services }}
{{- $svc := mergeOverwrite (deepCopy $.Values.default) (deepCopy $svc) }}
{{- if and $svc.enabled $svc.hpa $svc.resources }}

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  minReplicas: {{ $svc.replicaCount }}
  maxReplicas: {{ $svc.hpa.maxReplicas }}
  metrics:
  {{- if $svc.hpa.cpuAvrageUtilization }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $svc.hpa.cpuAvrageUtilization }}
  {{- end }}
  {{- if $svc.hpa.memoryAvrageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $svc.hpa.memoryAvrageUtilization }}
  {{- end }}
{{- end }}
{{- end }}
