{{- range $fullName, $svc := .Values.services }}
{{- $svc := mergeOverwrite (deepCopy $.Values.default) (deepCopy $svc) }}
{{- if and $svc.enabled $svc.service $svc.ingress }}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
{{- if $svc.ingress.annotations }}
  annotations:
{{ toYaml $svc.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if $svc.ingress.tls }}
  tls:
{{ toYaml $svc.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- if $svc.ingress.hosts }}
  {{- range $host := $svc.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
        {{- range $path := $svc.ingress.paths }}
          - path: {{ tpl $path $ }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ (index $svc.service 0).port }}
        {{- end -}}
  {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}
