apiVersion: apps/v1
kind: Deployment
metadata: 
  name: helloworld-deployment
  labels:
    app: helloworld
    environment: QA
    department: IT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        environment: QA
        department: IT
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo:2
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          tcpSocket:
            host:
            port: 3000
