apiVersion: v1
kind: Service
metadata: 
  name: dotnet-service

spec:
  ports:
  - port: 32001
    nodePort: 32001
    targetPort: 80
    protocol: TCP
  selector:
    app: dotnet-hello
  type: NodePort    
  